import type { Metadata } from "next";
import { Inter } from "next/font/google";
// Styles
// @ts-ignore
import "../app/style/main.css";

import Footer from "@/app/common/Footer";
import Header from "@/app/common/Header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        <Header />
        <div className='wrapper'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
